WIN_WIDTH = 800
WIN_HEIGHT = 600
TILESIZE = 20
STEPS = 1
FPS = 60

PLAYER_LAYER = 4
HOUSE_LAYER = 3
BLOCKS_LAYER = 2
GROUND_LAYER = 1
PUZZLE_LAYER = 5

PLAYER_STEPS = 3

BLACK = (0,0,0)

# 40 characters across, G, W, I, D, S
tilemap = [
    'IIIIIIIIIIIIIIIIIWWWWWIIIIIIIIIIIIIIIIII',
    'IIIIIIIIIIIIIIIIIIIIIWWWIIIIIIIIIIIIIWWW',
    'IIIIIIIIIIIIIIIIIIIIIIWWWWIIIIIIIIIWWWII',
    'IIIIIIIIIIIIIIIIIIIIIIIWWWWWWWWWWWWWIIII',
    'IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIWWWWIIIIII',
    'IIDDDDDIIIIIIIIIDDDDDDDIIIIIIIIIIWWWWIII',
    'IDGGGGGDDDDDDDDDDGGGGGGDDDDDIIIIIIIWWWII',
    'DGPGGGGGGGGGGGGGGGGGGGGGGGGGDDIIIIIIWWWW',
    'GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGDDDIIIIIII',
    'GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGDIIIII',
    'GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGDDDDD',
    'GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG',
    'GGGGGGGGGGGGGGGGSSSSSSGGGGGGGGGGGGGGGGGG',
    'GGGGGGGGGGGGGGGSWWWWWWSGGGGGGGGGGGGGGGGG',
    'GGGGGGGGGGGGGGSWWWWWWWWSGGGGGGGGGGGGGGGG',
    'GGGGGGGGGGGGGGGSWWWWWWWSGGGGGGGGGGGGGGGG',
    'GGGGGGGGGGGGGGGGSSSSSSSGGGGGGGGGGGGGGGGG',
    'GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG',
    'GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG',
    'GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG',
    'GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG',
    'SSSSSSGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG',
    'SSSSSSSSSSSSGGGGGGGGGGGGGGGGGGGGGGGGGGGG',
    'WWWWWWWWWSSSSSSGGGGGGGGGGGGGGGGGGGGGGGGG',
    'WWWWWWWWWWWSSSGGGGGGGGGGGGGGGGGGGGGGGGGG',
    'WWWWWWWWWSSSSSGGGGGGGGGGGGGGGGGGGGGGGGGG',
    'WWWWWWWWWWWWSSSSGGGGGGGGGGGGGGGGGGGGGGGG',
    'WWWWWWWWWWWWSSSSSGGGGGGGGGGGGGGGGGGGGGGG',
    'WWWWWWWWWWSSSSGGGGGGGGGGGGGGGGGGGGGGGGGG',
    'WWWWWSSSSSSSSGGGGGGGGGGGGGGGGGGGGGGGGGGG',

]
